In [1]:
%load_ext rpy2.ipython

/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:14: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Index as PandasIndex
/usr/local/lib/python3.6/dist-packages/rpy2/robjects/pandas2ri.py:34: UserWarning: pandas >= 1.0 is not supported.
  warnings.warn('pandas >= 1.0 is not supported.')

### Датасет, с которым мы будем работать

In [3]:
!wget https://stepic.org/media/attachments/lesson/11481/evals.csv

--2020-04-06 17:21:22--  https://stepic.org/media/attachments/lesson/11481/evals.csv
Resolving stepic.org (stepic.org)... 13.69.75.239
Connecting to stepic.org (stepic.org)|13.69.75.239|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55469 (54K) [application/octet-stream]
Saving to: ‘evals.csv’

evals.csv           100%[===================>]  54.17K   205KB/s    in 0.3s

2020-04-06 17:21:24 (205 KB/s) - ‘evals.csv’ saved [55469/55469]

Когда вы запускаете R, автоматически загружаются основные библиотеки для работы. В их числе библиотека datasets, в которой хранятся наборы данных из разных исследований. Чтобы просмотреть весь список доступных датасетов, выполните команду library(help = "datasets"). Некоторые из этих датасетов мы будем использовать в наших задачах. Они доступны по имени в любой момент работы. Например, если вы захотите использовать датасет mtcars, можете просто выполнить команду mtcars, чтобы увидеть данные в консоли.

Команда data(mtcars) добавит датасет в рабочую среду. 

Команда help(mtcars) выведет информацию о датасете.

Команда my_data <- mtcars запишет датасет в новую переменную.

В этой задче поработаем со встроенными данными mtcars. В датафрэйме mtcars создайте новую колонку (переменную) под названием even_gear, в которой будут единицы, если значение переменной (gear) четное, и нули если количество нечетное.   

Подсказка: вам может помочь оператор деления с остатком:
```
5 %% 2 == 1

TRUE
```

In [15]:
%%R 
mtcars$even_gear <- (mtcars$gear+1) %% 2 
mtcars$even_gear

 [1] 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1

Продолжим нашу работу с данными mtcars. Теперь ваша задача создать переменную - вектор mpg_4 и сохранить в нее значения расхода топлива (mpg) для машин с четырьмя цилиндрами (cyl).

In [18]:
%%R 
mpg_4 <- mtcars$mpg[mtcars$cyl == 4]
mpg_4

 [1] 22.8 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26.0 30.4 21.4

А теперь научимся отбирать только некоторые строчки из исходных данных. 

Ваша задача создать новый dataframe под названием mini_mtcars, в котором будут сохранены только третья, седьмая, десятая, двенадцатая и последняя строчка датафрейма mtcars.

In [35]:
%%R
mini_mtcars <- mtcars[c(3, 7, 10, 12, nrow(mtcars)),]
mini_mtcars

            mpg cyl  disp  hp drat   wt  qsec vs am gear carb even_gear
Datsun 710 22.8   4 108.0  93 3.85 2.32 18.61  1  1    4    1         1
Duster 360 14.3   8 360.0 245 3.21 3.57 15.84  0  0    3    4         0
Merc 280   19.2   6 167.6 123 3.92 3.44 18.30  1  0    4    4         1
Merc 450SE 16.4   8 275.8 180 3.07 4.07 17.40  0  0    3    3         0
Volvo 142E 21.4   4 121.0 109 4.11 2.78 18.60  1  1    4    2         1

Укажите какая команда создаст сабсет данных mtcars, только для тех автомобилей, у которых число цилиндров (cyl) не равняется 3, и время разгона автомобиля (qsec) больше среднего по выборке.

- [ ] new_data <- subset(mtcars, cyl == 3 | qsec > mean(qsec))

- [ ] new_data <- subset(mtcars, cyl == 3 & qsec < mean(qsec))

- [x] new_data <- subset(mtcars, cyl != 3 & qsec > mean(qsec))

- [ ] new_data <- subset(mtcars, cyl != 3 | qsec < mean(qsec))